theme: jekyll-theme-cayman
title: Strauss Website
description: Study of toxicity in far right channel videos and clusters on youtube using the YouNiverse dataset. The goal is to see if these channels generate more toxic behavior and isolate users.
show_downloads: True
navigation:
  - title: Home 
    url: Homepage
  - title: Data Story
    url: story
  - title: Thanks & Credentials
    url: thanks
  - title: Team
    url: team
  
